"""add inviter_id to invitations

Revision ID: 3e756dd5a072
Revises: b68e92344de9
Create Date: 2026-07-17 08:19:28.711819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e756dd5a072'
down_revision: Union[str, Sequence[str], None] = 'b68e92344de9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitations', sa.Column('inviter_id', sa.UUID(), nullable=False))
    op.create_foreign_key(op.f('fk_invitations_inviter_id_users'), 'invitations', 'users', ['inviter_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_invitations_inviter_id_users'), 'invitations', type_='foreignkey')
    op.drop_column('invitations', 'inviter_id')
    # ### end Alembic commands ###
