"""add oauth accounts

Revision ID: 9db0b06a4cae
Revises: 3e756dd5a072
Create Date: 2026-07-17 08:38:33.804839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9db0b06a4cae'
down_revision: Union[str, Sequence[str], None] = '3e756dd5a072'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('workspaces',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspaces'))
    )
    op.create_index(op.f('ix_workspaces_slug'), 'workspaces', ['slug'], unique=True)
    op.create_table('invitations',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('inviter_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MANAGER', 'DEVELOPER', name='workspacerole'), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', 'EXPIRED', 'CANCELLED', name='invitationstatus'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inviter_id'], ['users.id'], name=op.f('fk_invitations_inviter_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_invitations_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invitations')),
    sa.UniqueConstraint('token', name=op.f('uq_invitations_token'))
    )
    op.create_index(op.f('ix_invitations_email'), 'invitations', ['email'], unique=False)
    op.create_index(op.f('ix_invitations_workspace_id'), 'invitations', ['workspace_id'], unique=False)
    op.create_index('uq_workspace_invite_email', 'invitations', ['workspace_id', 'email'], unique=True, postgresql_where=sa.text("status = 'PENDING'"))
    op.create_table('oauth_accounts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('LOCAL', 'GITHUB', 'GOOGLE', 'AZURE', name='authprovider'), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('access_token', sa.String(length=1000), nullable=True),
    sa.Column('refresh_token', sa.String(length=1000), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_oauth_accounts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_oauth_accounts')),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_provider_user_id')
    )
    op.create_table('password_reset_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_password_reset_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_password_reset_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_password_reset_tokens_token_hash'))
    )
    op.create_table('repositories',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('GITHUB', 'GITLAB', 'AZURE_DEVOPS', name='repositoryprovider'), nullable=False),
    sa.Column('provider_repo_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('repo_url', sa.String(length=500), nullable=True),
    sa.Column('clone_url', sa.String(length=500), nullable=True),
    sa.Column('default_branch', sa.String(length=100), nullable=False),
    sa.Column('visibility', sa.String(length=50), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('webhook_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_repositories_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_repositories')),
    sa.UniqueConstraint('workspace_id', 'provider', 'provider_repo_id', name='uq_workspace_provider_repo')
    )
    op.create_index(op.f('ix_repositories_provider_repo_id'), 'repositories', ['provider_repo_id'], unique=False)
    op.create_index(op.f('ix_repositories_workspace_id'), 'repositories', ['workspace_id'], unique=False)
    op.create_table('workspace_members',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MANAGER', 'DEVELOPER', name='workspacerole'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_workspace_members_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_workspace_members_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspace_members')),
    sa.UniqueConstraint('workspace_id', 'user_id', name='uq_workspace_user')
    )
    op.create_index(op.f('ix_workspace_members_user_id'), 'workspace_members', ['user_id'], unique=False)
    op.create_index(op.f('ix_workspace_members_workspace_id'), 'workspace_members', ['workspace_id'], unique=False)
    op.create_table('webhook_events',
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('delivery_id', sa.String(length=255), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('processing_status', sa.Enum('RECEIVED', 'PROCESSED', 'IGNORED', 'FAILED', name='webhookprocessingstatus'), server_default='RECEIVED', nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name=op.f('fk_webhook_events_repository_id_repositories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_events'))
    )
    op.create_index(op.f('ix_webhook_events_delivery_id'), 'webhook_events', ['delivery_id'], unique=True)
    op.create_index(op.f('ix_webhook_events_repository_id'), 'webhook_events', ['repository_id'], unique=False)
    op.create_table('commits',
    sa.Column('repository_id', sa.UUID(), nullable=False, comment='The connected repository this commit belongs to.'),
    sa.Column('webhook_event_id', sa.UUID(), nullable=False, comment='The raw webhook delivery that produced this commit record.'),
    sa.Column('github_commit_sha', sa.String(length=40), nullable=False, comment='Full 40-character git commit SHA — canonical identifier.'),
    sa.Column('short_sha', sa.String(length=8), nullable=False, comment='First 8 characters of the SHA — for display purposes.'),
    sa.Column('commit_message', sa.Text(), nullable=False, comment='Full commit message body as provided by GitHub.'),
    sa.Column('commit_url', sa.String(length=500), nullable=False, comment='GitHub HTML URL to the commit (e.g. https://github.com/owner/repo/commit/sha).'),
    sa.Column('committed_at', sa.DateTime(timezone=True), nullable=False, comment='Authoritative commit timestamp from the GitHub payload (timezone-aware).'),
    sa.Column('branch', sa.String(length=255), nullable=False, comment="Branch the push targeted, parsed from payload ref (e.g. 'main')."),
    sa.Column('author_name', sa.String(length=255), nullable=False, comment='Git author name field from the commit.'),
    sa.Column('author_email', sa.String(length=255), nullable=False, comment='Git author email — used for Developer Dashboard attribution queries.'),
    sa.Column('author_username', sa.String(length=255), nullable=True, comment='GitHub username of the author — absent for non-GitHub users.'),
    sa.Column('added_files', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False, comment='List of file paths added in this commit.'),
    sa.Column('modified_files', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False, comment='List of file paths modified in this commit.'),
    sa.Column('removed_files', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False, comment='List of file paths removed in this commit.'),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Full raw commit object from the GitHub push payload — used by AI processing in Milestone 6.'),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='commitstatus'), server_default='PENDING', nullable=False, comment='Processing lifecycle state. PENDING until a background worker picks this up.'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name=op.f('fk_commits_repository_id_repositories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['webhook_event_id'], ['webhook_events.id'], name=op.f('fk_commits_webhook_event_id_webhook_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_commits')),
    sa.UniqueConstraint('github_commit_sha', 'repository_id', name='uq_commits_sha_repository_id')
    )
    op.create_index(op.f('ix_commits_author_email'), 'commits', ['author_email'], unique=False)
    op.create_index(op.f('ix_commits_committed_at'), 'commits', ['committed_at'], unique=False)
    op.create_index(op.f('ix_commits_repository_id'), 'commits', ['repository_id'], unique=False)
    op.create_index('ix_commits_repository_id_committed_at', 'commits', ['repository_id', 'committed_at'], unique=False)
    op.create_index(op.f('ix_commits_status'), 'commits', ['status'], unique=False)
    op.create_index(op.f('ix_commits_webhook_event_id'), 'commits', ['webhook_event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_commits_webhook_event_id'), table_name='commits')
    op.drop_index(op.f('ix_commits_status'), table_name='commits')
    op.drop_index('ix_commits_repository_id_committed_at', table_name='commits')
    op.drop_index(op.f('ix_commits_repository_id'), table_name='commits')
    op.drop_index(op.f('ix_commits_committed_at'), table_name='commits')
    op.drop_index(op.f('ix_commits_author_email'), table_name='commits')
    op.drop_table('commits')
    op.drop_index(op.f('ix_webhook_events_repository_id'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_delivery_id'), table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index(op.f('ix_workspace_members_workspace_id'), table_name='workspace_members')
    op.drop_index(op.f('ix_workspace_members_user_id'), table_name='workspace_members')
    op.drop_table('workspace_members')
    op.drop_index(op.f('ix_repositories_workspace_id'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_provider_repo_id'), table_name='repositories')
    op.drop_table('repositories')
    op.drop_table('password_reset_tokens')
    op.drop_table('oauth_accounts')
    op.drop_index('uq_workspace_invite_email', table_name='invitations', postgresql_where=sa.text("status = 'PENDING'"))
    op.drop_index(op.f('ix_invitations_workspace_id'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_email'), table_name='invitations')
    op.drop_table('invitations')
    op.drop_index(op.f('ix_workspaces_slug'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
