"""add user_id to repository

Revision ID: b3c5b3918b3e
Revises: 2020d9686e7f
Create Date: 2026-08-06 15:38:56.475743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3c5b3918b3e'
down_revision: Union[str, None] = '2020d9686e7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'repositories', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'repositories', type_='foreignkey')
    op.drop_column('repositories', 'user_id')
    # ### end Alembic commands ###
